backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

media_library:
  name: uploadcare
  config:
    publicKey: 5429a01c0d6f3fa25741
    imageShrink: '800x600'

collections:
  - name: 'blog-en'
    label: 'Blog in english'
    folder: 'src/pages/blog'
    filter: { field: 'language', value: 'en' }
    extension: '.en.md'
    format: 'frontmatter'
    create: true
    slug: '{{title}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post.en',
        }
      - { label: 'Language', name: 'language', widget: 'hidden', default: 'en' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Featured Post', name: 'featuredpost', widget: 'boolean' }
      - {
          label: 'Link to spanish version',
          name: 'translatedSlug',
          widget: 'string',
          required: false,
        }
      - { label: 'Featured Image', name: 'featuredimage', widget: image }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: 'blog-es'
    label: 'Blog en español'
    folder: 'src/pages/blog'
    filter: { field: 'language', value: 'es' }
    extension: '.es.md'
    format: 'frontmatter'
    create: true
    slug: '{{title}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post.es',
        }
      - { label: 'Lenguaje', name: 'language', widget: 'hidden', default: 'es' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime' }
      - { label: 'Descripción', name: 'description', widget: 'text' }
      - {
          label: 'Publicación destacada',
          name: 'featuredpost',
          widget: 'boolean',
        }
      - {
          label: 'Enlace a la versión en inglés',
          name: 'translatedSlug',
          widget: 'string',
          required: false,
        }
      - { label: 'Imágen destacada', name: 'featuredimage', widget: image }
      - { label: 'Cuerpo', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.en.md'
        label: 'Landing Page (English)'
        name: 'index-en'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page.en',
            }
          - {
              label: 'Language',
              name: 'language',
              widget: 'hidden',
              default: 'en',
            }
          - { label: 'Title', name: title, widget: string }
          - { label: 'Image', name: image, widget: image }
          - { label: 'Heading', name: heading, widget: string }
          - { label: 'Subheading', name: subheading, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
      - file: 'src/pages/index.es.md'
        label: 'Landing Page (Spanish)'
        name: 'index-es'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page.es',
            }
          - {
              label: 'Language',
              name: 'language',
              widget: 'hidden',
              default: 'es',
            }
          - { label: 'Título', name: title, widget: string }
          - { label: 'Imágen', name: image, widget: image }
          - { label: 'Cabecera', name: heading, widget: string }
          - { label: 'Sub-cabecera', name: subheading, widget: string }
          - {
              label: 'Campo principal',
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: 'Título', name: title, widget: string },
                  { label: 'Descripción', name: description, widget: text },
                ],
            }
          - { label: 'Descripción', name: description, widget: string }
          - {
              label: 'Introducción',
              name: intro,
              widget: object,
              fields:
                [
                  { label: 'Cabecera', name: heading, widget: string },
                  { label: 'Descripción', name: description, widget: text },
                  {
                    label: 'Promociones',
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: 'Imágen', name: image, widget: image },
                        { label: 'Texto', name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: 'Principal',
              name: main,
              widget: object,
              fields:
                [
                  { label: 'Cabecera', name: heading, widget: string },
                  { label: 'Descripción', name: description, widget: text },
                  {
                    label: '1ra imágen',
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: 'Imágen', name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: '2da imágen',
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: 'Imágen', name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: '3ra imágen',
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: 'Imágen', name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
      - file: 'src/pages/about/index.en.md'
        label: 'About (English)'
        name: 'about-en'
        slug: '{{title}}'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page.en',
            }
          - {
              label: 'Language',
              name: 'language',
              widget: 'hidden',
              default: 'en',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'src/pages/about/index.es.md'
        label: 'About (Spanish)'
        name: 'about-es'
        slug: '{{title}}'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page.es',
            }
          - {
              label: 'Language',
              name: 'language',
              widget: 'hidden',
              default: 'es',
            }
          - { label: 'Título', name: 'title', widget: 'string' }
          - { label: 'Cuerpo', name: 'body', widget: 'markdown' }
